/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StationssScheduleImport } from './routes/stationss/$schedule'
import { Route as StationsScheduleImport } from './routes/stations/$schedule'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StationssScheduleRoute = StationssScheduleImport.update({
  id: '/stationss/$schedule',
  path: '/stationss/$schedule',
  getParentRoute: () => rootRoute,
} as any)

const StationsScheduleRoute = StationsScheduleImport.update({
  id: '/stations/$schedule',
  path: '/stations/$schedule',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/stations/$schedule': {
      id: '/stations/$schedule'
      path: '/stations/$schedule'
      fullPath: '/stations/$schedule'
      preLoaderRoute: typeof StationsScheduleImport
      parentRoute: typeof rootRoute
    }
    '/stationss/$schedule': {
      id: '/stationss/$schedule'
      path: '/stationss/$schedule'
      fullPath: '/stationss/$schedule'
      preLoaderRoute: typeof StationssScheduleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/stations/$schedule': typeof StationsScheduleRoute
  '/stationss/$schedule': typeof StationssScheduleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/stations/$schedule': typeof StationsScheduleRoute
  '/stationss/$schedule': typeof StationssScheduleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/stations/$schedule': typeof StationsScheduleRoute
  '/stationss/$schedule': typeof StationssScheduleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/stations/$schedule'
    | '/stationss/$schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/stations/$schedule'
    | '/stationss/$schedule'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/stations/$schedule'
    | '/stationss/$schedule'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  StationsScheduleRoute: typeof StationsScheduleRoute
  StationssScheduleRoute: typeof StationssScheduleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  StationsScheduleRoute: StationsScheduleRoute,
  StationssScheduleRoute: StationssScheduleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo/tanstack-query",
        "/stations/$schedule",
        "/stationss/$schedule"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/stations/$schedule": {
      "filePath": "stations/$schedule.tsx"
    },
    "/stationss/$schedule": {
      "filePath": "stationss/$schedule.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
